# Generated by Django 5.2 on 2025-06-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/')),
                ('name', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('range', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_location', models.CharField(blank=True, max_length=500, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, to='tags.tag')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
