# Generated by Django 5.2 on 2025-06-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['type', 'name']},
        ),
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('general', 'General'), ('genre', 'Genre'), ('miniature', 'Miniature'), ('terrain', 'Terrain'), ('style', 'Style'), ('faction', 'Faction'), ('scale', 'Scale'), ('other', 'Other')], default='general', max_length=20),
        ),
    ]
