# Generated by Django 5.2 on 2025-06-02 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_auto_20250602_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_type__sort_order', 'tag_type__name', 'name']},
        ),
    ]
