# Generated by Django 5.2 on 2025-06-02 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_alter_tag_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
    ]
