# Generated by Django 5.2 on 2025-06-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20250602_1050'),
        ('tags', '0004_tagtype_alter_tag_options_tag_type_old_and_more'),
        ('tags', '0006_remove_tag_type'),
    ]

    operations = [
    ]
