# Generated by Django 5.2 on 2025-06-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0007_merge_20250602_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag_type__sort_order', 'tag_type__name', 'name']},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='type_old',
        ),
    ]
